---
# tasks file for cpanel-exporter-role

- name: Download cpanel_exporter
  get_url:
    url: "https://github.com/ralfonso-directnic/cpanel_exporter/releases/download/1.0/cpanel_exporter-1.0.linux.amd64"
    dest: /usr/local/bin/cpanel_exporter
    mode: "+x"
  become: true

# Create systemd service file from template
- name: Create systemd service file from template
  template:
    dest: /etc/systemd/system/cpanel_exporter.service
    src: cpanel_exporter.service.j2
  become: true

# Enable and start service

- name: Enable and start service
  systemd:
    name: cpanel_exporter
    enabled: true
    state: started
    daemon_reload: yes
  become: true