---
# tasks file for cpanel-exporter-role

# Chack if this is a cPanel server
- name: Check if cPanel is installed
  stat:
    path: /usr/local/cpanel/version
  register: cpanel_installed

- name: Include install tasks if the cPanel is installed
  include_tasks: install.yml
  when: cpanel_installed.stat.exists